In [1]:
import pandas as pd
import numpy as np

In [2]:
cars = pd.read_csv('car.csv')
cars.head(10)

  buying  maint doors persons lug_boot safety verdict
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc
5  vhigh  vhigh     2       2      med   high   unacc
6  vhigh  vhigh     2       2      big    low   unacc
7  vhigh  vhigh     2       2      big    med   unacc
8  vhigh  vhigh     2       2      big   high   unacc
9  vhigh  vhigh     2       4    small    low   unacc

In [3]:
cars.describe()

       buying maint doors persons lug_boot safety verdict
count    1728  1728  1728    1728     1728   1728    1728
unique      4     4     4       3        3      3       4
top       med   med     3    more      med    med   unacc
freq      432   432   432     576      576    576    1210

In [4]:
delays = pd.read_csv('delays.csv')
delays.head(10)

,Loco,Code,Class,SDep,HDEP,PLACE,DEFECT,VERIFIED DEFECTS,DELAYS,Shift,Trac Li,DelayDate,Driver,Artisan,RefNum
0,36284,BRAKES,36,XNS,NELSPRUIT,KROONSTAD,TO SETUP BRAKES FOR DRIVER,CALL CANCELLED DUE TO NO BRAKE HANDLES,-,N,NO,2017/04/01 00:00,M. RAMPHETENG,K. LEBOKE,5R04/06
1,36041,BAR/START,36,XSW,SWARTKOPS,PORT ELIZABETH,LOCO TO BAR NAD START,BAR AND STARTED LOCO,-,D,NO,2017/04/01 00:00,J VAN ZYL,N ZIMBA,3R04/3012
2,18009,AXLE PROBE,18E,XTQ,WELGEDAG,WELGEDAGT,AXLE PROBE FAULT INDICATION,NO FAULT FOUND,-,D,NO,2017/04/01 00:00,A KONANE,A KHAN,7R04/3013
3,18745,VACUUM,18E,XTQ,COLIGNY,SENTRARAND,LOCO NOT CREATING VACUUM,NO FAULT FOUND,-,D,NO,2017/04/01 00:00,J BARNAARD,M MAKGATO,7R04/3017
4,18164,B1INVERTER,18E,XUB,UMBILO,BON ACCORD,B1INVERTER NOT WORKING,VR NOT WORKING. WFS,-,D,YES,2017/04/01 00:00,G REEDER,W SITHOLE,8R04/3018
5,44020,INSPECTION,44,XWI,OGIES,SPRINGS,LOCO FOR DAILY INSPECTION,DAILY INSPECTION COMPLETED,-,D,NO,2017/04/01 00:00,C LUTHERWYK,M BATHOBAKAE,7R04/3020
6,44033,INSPECTION,44,XWI,OGIES,SPRINGS,LOCO FOR DAILY INSPECTION,DAILY INSPECTION COMPLETED,-,D,NO,2017/04/01 00:00,C LUTHERWYK,M BATHOBAKAE,7R04/3020
7,18086,CBR,18E,XUB,UMBILO,KATBOSFONTEIN,CBR TRIPS,LOCO TESTED IN ORDER,-,N,NO,2017/04/01 00:00,M.NZALA,M.MAKGETHA,7R04/3001
8,18314,PIPE,18E,XNS,WITBANK,WITBANK,NO.2 SIGNAL PIPE MISSING,REPLACED NO.2 SIGNAL PIPE,-,D,NO,2017/04/01 00:00,F TSHETSI,C MOTEDI,8R04/3022
9,18861,NOOP,18E,XTQ,SENTRARAND,VEERTIENSTROME,NO TRACTION POWER,SECURED SPEEDO BOX PLUG,-,D,YES,2017/04/01 00:00,P.A.GABOUTLWETLWE,I.VAN WYK,2R04/27

In [5]:
delays.index = delays.RefNum

In [6]:
delays.head(5)

,Loco,Code,Class,SDep,HDEP,PLACE,DEFECT,VERIFIED DEFECTS,DELAYS,Shift,Trac Li,DelayDate,Driver,Artisan,RefNum
RefNum,,,,,,,,,,,,,,,
5R04/06,36284,BRAKES,36,XNS,NELSPRUIT,KROONSTAD,TO SETUP BRAKES FOR DRIVER,CALL CANCELLED DUE TO NO BRAKE HANDLES,-,N,NO,2017/04/01 00:00,M. RAMPHETENG,K. LEBOKE,5R04/06
3R04/3012,36041,BAR/START,36,XSW,SWARTKOPS,PORT ELIZABETH,LOCO TO BAR NAD START,BAR AND STARTED LOCO,-,D,NO,2017/04/01 00:00,J VAN ZYL,N ZIMBA,3R04/3012
7R04/3013,18009,AXLE PROBE,18E,XTQ,WELGEDAG,WELGEDAGT,AXLE PROBE FAULT INDICATION,NO FAULT FOUND,-,D,NO,2017/04/01 00:00,A KONANE,A KHAN,7R04/3013
7R04/3017,18745,VACUUM,18E,XTQ,COLIGNY,SENTRARAND,LOCO NOT CREATING VACUUM,NO FAULT FOUND,-,D,NO,2017/04/01 00:00,J BARNAARD,M MAKGATO,7R04/3017
8R04/3018,18164,B1INVERTER,18E,XUB,UMBILO,BON ACCORD,B1INVERTER NOT WORKING,VR NOT WORKING. WFS,-,D,YES,2017/04/01 00:00,G REEDER,W SITHOLE,8R04/3018

In [7]:
delays.describe()

               Loco
count  28091.000000
mean   23970.709551
std    10833.519973
min     1230.000000
25%    18120.000000
50%    18779.000000
75%    34902.000000
max    45020.000000

In [9]:
import sklearn as sk
from kmodes import kmodes

# random categorical data
data = np.random.choice(20, (100, 10))

km = kmodes.KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 24, cost: 799.0
Run 1, iteration: 2/100, moves: 8, cost: 793.0
Run 1, iteration: 3/100, moves: 3, cost: 791.0
Run 1, iteration: 4/100, moves: 2, cost: 790.0
Run 1, iteration: 5/100, moves: 1, cost: 790.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 23, cost: 792.0
Run 2, iteration: 2/100, moves: 3, cost: 792.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 19, cost: 791.0
Run 3, iteration: 2/100, moves: 1, cost: 791.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 18, cost: 798.0
Run 4, iteration: 2/100, moves: 10, cost: 796.0
Run 4, iteration: 3/100, moves: 1, cost: 796.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 20, cost: 794.0
Run 5, iteration: 2/100, moves: 9, cost: 790.0
Run 5, iteration: 3/100, moves: 4, cost: 787.0
Run 5, iteration: 4/100, moves: 1, cost: 787.0
Best run was number 5
[[ 5 10  1  7  4  4  0 16  6  0]
 [ 7 15  8  4  5 15 14 18  0  7]
 [16 16 15  3  1 11  6 13  6 14]
 [11 18 13  6  2 13 12 19 19  2]]

In [18]:
cars1 = pd.read_csv('cars1.csv')
data =cars1.values

print data

[[0 0 0 ..., 0 2 0]
 [0 0 0 ..., 0 1 0]
 [0 0 0 ..., 0 2 0]
 ...,
 [1 1 3 ..., 2 2 0]
 [1 1 3 ..., 2 1 2]
 [1 1 3 ..., 2 2 3]]

In [19]:
km = kmodes.KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 5324.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 0, cost: 5189.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 150, cost: 5170.0
Run 3, iteration: 2/100, moves: 0, cost: 5170.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 0, cost: 5342.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 238, cost: 5093.0
Run 5, iteration: 2/100, moves: 0, cost: 5093.0
Best run was number 5
[[1 1 1 0 0 2 0]
 [1 1 1 1 1 2 1]
 [1 2 3 0 2 2 0]]

In [44]:
cars = pd.read_csv('car.csv')
print cars.head(10)

data = cars

km = kmodes.KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

  buying  maint doors persons lug_boot safety verdict
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc
5  vhigh  vhigh     2       2      med   high   unacc
6  vhigh  vhigh     2       2      big    low   unacc
7  vhigh  vhigh     2       2      big    med   unacc
8  vhigh  vhigh     2       2      big   high   unacc
9  vhigh  vhigh     2       4    small    low   unacc
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 0, cost: 6131.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 0, cost: 6088.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 0, cost: 6243.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 0, cost: 6326.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 0, cost: 6254.0
Best run was number 2

In [24]:

# Print the cluster centroids
print(km.cluster_centroids_)

[['vhigh' 'high' '4' '4' 'big' 'high' 'unacc']
 ['med' 'med' '5more' '4' 'big' 'med' 'acc']
 ['vhigh' 'med' '3' '2' 'med' 'low' 'unacc']]

In [26]:
print km.cost_
print km.n_iter_

6128.0
1

In [53]:
# for r, c in zip(data.values,clusters):
#     print("cluster:{}".format(c),r)

clusters.shape

data_arr = data.values
# print data

# print clusters.reshape(-1,1)

classified_data = np.hstack((data_arr, clusters.reshape(-1,1)))
print classified_data

[['vhigh' 'vhigh' '2' ..., 'low' 'unacc' 1]
 ['vhigh' 'vhigh' '2' ..., 'med' 'unacc' 1]
 ['vhigh' 'vhigh' '2' ..., 'high' 'unacc' 1]
 ...,
 ['low' 'low' '5more' ..., 'low' 'unacc' 0]
 ['low' 'low' '5more' ..., 'med' 'good' 0]
 ['low' 'low' '5more' ..., 'high' 'vgood' 2]]

In [68]:
clusterlist0 = []
clusterlist1 = []
clusterlist2 = []

for r in classified_data:
    if r[7] == 0:
        clusterlist0.append(r)
    elif r[7] == 1:
        clusterlist1.append(r)
    elif r[7] == 2:
        clusterlist2.append(r)

print len(clusterlist0)
print len(clusterlist1)
print len(clusterlist2)

776
527
425

In [78]:
# cat_type = CategoricalDtype(categories=["vhigh", "high", "low","vlow"],ordered=True)
col = ["buying","maint","doors", "persons", "lug_boot", "safety", "verdict","mode"]
cardf = pd.DataFrame(classified_data, columns = col)

In [80]:
print cardf.head()

  buying  maint doors persons lug_boot safety verdict mode
0  vhigh  vhigh     2       2    small    low   unacc    1
1  vhigh  vhigh     2       2    small    med   unacc    1
2  vhigh  vhigh     2       2    small   high   unacc    1
3  vhigh  vhigh     2       2      med    low   unacc    1
4  vhigh  vhigh     2       2      med    med   unacc    1

In [81]:
print cardf.describe()

       buying maint doors persons lug_boot safety verdict  mode
count    1728  1728  1728    1728     1728   1728    1728  1728
unique      4     4     4       3        3      3       4     3
top       med   med     3    more      med    med   unacc     0
freq      432   432   432     576      576    576    1210   776

In [101]:
for d in cardf:
    cardf[d] = cardf[d].astype('category')
#     print cardf[d].dtype
    print "category: ", d
    print cardf[d].value_counts()
    
    
#     print cardf[d].cat.categorical

category:  buying
vhigh    432
med      432
low      432
high     432
Name: buying, dtype: int64
category:  maint
vhigh    432
med      432
low      432
high     432
Name: maint, dtype: int64
category:  doors
5more    432
4        432
3        432
2        432
Name: doors, dtype: int64
category:  persons
more    576
4       576
2       576
Name: persons, dtype: int64
category:  lug_boot
small    576
med      576
big      576
Name: lug_boot, dtype: int64
category:  safety
med     576
low     576
high    576
Name: safety, dtype: int64
category:  verdict
unacc    1210
acc       384
good       69
vgood      65
Name: verdict, dtype: int64
category:  mode
0    776
1    527
2    425
Name: mode, dtype: int64

In [138]:
centroids = km.cluster_centroids_
modelist = []
modelist.append(cardf[cardf["mode"] == 0])
modelist.append(cardf[cardf["mode"] == 1])
modelist.append(cardf[cardf["mode"] == 2])
print len(modelist)

for i in range(3):
    print modelist[i].shape

# for d in modelist[2]:
#     cardf[d] = cardf[d].astype('category')
#     print "category: ", d
#     print cardf[d].value_counts()
for d in modelist[0]:
    print "category: ", d, "------------------------>"
    for i in range(3):
        print "Mode ", i, centroids[i]
#         modelist[i][d] = modelist[i][d].astype('category')
        print modelist[i][d].value_counts(normalize=True)
  
# for i in range(3):
#     print modelist[i].apply(pd.Series.value_counts(normalize=True))
# # print cardf.apply(pd.value_counts)

3
(776, 8)
(527, 8)
(425, 8)
category:  buying ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
vhigh    0.314433
high     0.251289
low      0.248711
med      0.185567
Name: buying, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
vhigh    0.278937
high     0.254269
low      0.250474
med      0.216319
Name: buying, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
med      0.409412
low      0.251765
high     0.242353
vhigh    0.096471
Name: buying, dtype: float64
category:  maint ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
med      0.390464
high     0.255155
vhigh    0.229381
low      0.125000
Name: maint, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
low      0.466793
high     0.237192
vhigh    0.204934
med      0.091082
Name: maint, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
vhigh    0.343529
high     0.256471
low      0.209412
med      0.190588
Name: maint, dtype: float64
category:  doors ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
3        0.297680
2        0.259021
5more    0.246134
4        0.197165
Name: doors, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
3        0.273245
2        0.265655
5more    0.250474
4        0.210626
Name: doors, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
4        0.395294
5more    0.256471
2        0.214118
3        0.134118
Name: doors, dtype: float64
category:  persons ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
4       0.528351
more    0.240979
2       0.230670
Name: persons, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
2       0.681214
more    0.233397
4       0.085389
Name: persons, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
more    0.625882
4       0.284706
2       0.089412
Name: persons, dtype: float64
category:  lug_boot ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
big      0.548969
med      0.257732
small    0.193299
Name: lug_boot, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
small    0.645161
med      0.263757
big      0.091082
Name: lug_boot, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
med      0.557647
big      0.240000
small    0.202353
Name: lug_boot, dtype: float64
category:  safety ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
low     0.449742
med     0.329897
high    0.220361
Name: safety, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
low     0.388994
med     0.337761
high    0.273245
Name: safety, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
high    0.614118
med     0.334118
low     0.051765
Name: safety, dtype: float64
category:  verdict ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
unacc    0.782216
acc      0.143041
good     0.041237
vgood    0.033505
Name: verdict, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
unacc    0.937381
acc      0.041746
good     0.020873
vgood    0.000000
Name: verdict, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
acc      0.590588
unacc    0.256471
vgood    0.091765
good     0.061176
Name: verdict, dtype: float64
category:  mode ------------------------>
Mode  0 ['vhigh' 'med' '3' '4' 'big' 'low' 'unacc']
0    1.0
2    0.0
1    0.0
Name: mode, dtype: float64
Mode  1 ['vhigh' 'low' '3' '2' 'small' 'low' 'unacc']
1    1.0
2    0.0
0    0.0
Name: mode, dtype: float64
Mode  2 ['med' 'vhigh' '4' 'more' 'med' 'high' 'acc']
2    1.0
1    0.0
0    0.0
Name: mode, dtype: float64

In [116]:
pd.crosstab(modelist[i].verdict,modelist[i][d].safety)

AttributeError: 'Series' object has no attribute 'safety'